### ISSUE TITLE
XBOX 360 Wireless triggering Exception "does not support haptics"

### ISSUE THREAD

**Issue by Seppo007** [lowkey42/medienprojekt#39]
See full report here:

http://pastebin.com/w2HidH2D

**Comment by lowkey42** [comment]
Scheint ein offener Bug in SDL2.0.3 zu sein: https://bugzilla.libsdl.org/show_bug.cgi?id=2612
Können wir dann wohl erstmal nichts machen und müssen unter Windows 8 auf Force-Feedback verzichten.
